name: "Biome"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci
